name: dnd_player_flutter
description: A new way to play D&D on your phone.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  equatable: ^2.0.3

  # logic
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.11

  # ui
  dotted_border: ^2.0.0

  
dev_dependencies:
  flutter_lints: ^1.0.4

  hive_generator: ^1.1.3
  build_runner: ^2.1.5
  test: ^1.20.1
  bloc_test: ^9.0.2
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    # jsons
    - assets/rules/en/races.json
    - assets/rules/en/traits.json
    - assets/rules/en/features.json
    - assets/rules/en/classes.json
    - assets/rules/en/skills.json
    - assets/rules/en/equipment.json
    - assets/rules/en/spells.json

    # stats
    - assets/drawable/stats/heart.png
    - assets/drawable/stats/sword.png
    - assets/drawable/stats/tent.png
    - assets/drawable/stats/shield.png
    - assets/drawable/stats/hammer.png
    - assets/drawable/stats/money.png
    - assets/drawable/stats/xp.png

    # dice
    - assets/drawable/dice/d20.png

    # money
    - assets/drawable/money/platinum.png
    - assets/drawable/money/gold.png
    - assets/drawable/money/electrum.png
    - assets/drawable/money/silver.png
    - assets/drawable/money/copper.png

    # class icons
    - assets/drawable/icons/fighter.png
    - assets/drawable/icons/barbarian.png
    - assets/drawable/icons/bard.png
    - assets/drawable/icons/cleric.png
    - assets/drawable/icons/paladin.png
    - assets/drawable/icons/ranger.png
    - assets/drawable/icons/rogue.png
    - assets/drawable/icons/sorcerer.png
    - assets/drawable/icons/warlock.png
    - assets/drawable/icons/wizard.png
    - assets/drawable/icons/druid.png
    - assets/drawable/icons/monk.png
    - assets/drawable/icons/2.0x/fighter.png
    - assets/drawable/icons/2.0x/barbarian.png
    - assets/drawable/icons/2.0x/bard.png
    - assets/drawable/icons/2.0x/cleric.png
    - assets/drawable/icons/2.0x/paladin.png
    - assets/drawable/icons/2.0x/ranger.png
    - assets/drawable/icons/2.0x/rogue.png
    - assets/drawable/icons/2.0x/sorcerer.png
    - assets/drawable/icons/2.0x/warlock.png
    - assets/drawable/icons/2.0x/wizard.png
    - assets/drawable/icons/2.0x/druid.png
    - assets/drawable/icons/2.0x/monk.png

    # shape
    - assets/drawable/shape/romb.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
