// Mocks generated by Mockito 5.0.16 from annotations
// in dnd_player_flutter/test/bloc/character_creator_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i13;

import 'package:dnd_player_flutter/data/characteristics.dart' as _i14;
import 'package:dnd_player_flutter/dto/character.dart' as _i10;
import 'package:dnd_player_flutter/dto/class.dart' as _i8;
import 'package:dnd_player_flutter/dto/equipment.dart' as _i11;
import 'package:dnd_player_flutter/dto/race.dart' as _i15;
import 'package:dnd_player_flutter/dto/skill.dart' as _i17;
import 'package:dnd_player_flutter/dto/spell.dart' as _i12;
import 'package:dnd_player_flutter/dto/trait.dart' as _i16;
import 'package:dnd_player_flutter/repository/character_repository.dart' as _i9;
import 'package:dnd_player_flutter/repository/classes_repository.dart' as _i4;
import 'package:dnd_player_flutter/repository/equipment_repository.dart' as _i6;
import 'package:dnd_player_flutter/repository/races_repository.dart' as _i3;
import 'package:dnd_player_flutter/repository/settings_repository.dart' as _i2;
import 'package:dnd_player_flutter/repository/skills_repository.dart' as _i5;
import 'package:hive/hive.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSettingsRepository_0 extends _i1.Fake
    implements _i2.SettingsRepository {}

class _FakeRacesRepository_1 extends _i1.Fake implements _i3.RacesRepository {}

class _FakeClassesRepository_2 extends _i1.Fake
    implements _i4.ClassesRepository {}

class _FakeSkillsRepository_3 extends _i1.Fake implements _i5.SkillsRepository {
}

class _FakeEquipmentRepository_4 extends _i1.Fake
    implements _i6.EquipmentRepository {}

class _FakeBox_5<E> extends _i1.Fake implements _i7.Box<E> {}

class _FakeProficiencyChoices_6 extends _i1.Fake
    implements _i8.ProficiencyChoices {}

/// A class which mocks [CharacterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRepository extends _i1.Mock
    implements _i9.CharacterRepository {
  MockCharacterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get settingsRepository =>
      (super.noSuchMethod(Invocation.getter(#settingsRepository),
          returnValue: _FakeSettingsRepository_0()) as _i2.SettingsRepository);
  @override
  _i3.RacesRepository get racesRepository =>
      (super.noSuchMethod(Invocation.getter(#racesRepository),
          returnValue: _FakeRacesRepository_1()) as _i3.RacesRepository);
  @override
  _i4.ClassesRepository get classesRepository =>
      (super.noSuchMethod(Invocation.getter(#classesRepository),
          returnValue: _FakeClassesRepository_2()) as _i4.ClassesRepository);
  @override
  _i5.SkillsRepository get skillsRepository =>
      (super.noSuchMethod(Invocation.getter(#skillsRepository),
          returnValue: _FakeSkillsRepository_3()) as _i5.SkillsRepository);
  @override
  _i6.EquipmentRepository get equipmentRepository => (super.noSuchMethod(
      Invocation.getter(#equipmentRepository),
      returnValue: _FakeEquipmentRepository_4()) as _i6.EquipmentRepository);
  @override
  _i7.Box<dynamic> get box => (super.noSuchMethod(Invocation.getter(#box),
      returnValue: _FakeBox_5<dynamic>()) as _i7.Box<dynamic>);
  @override
  set box(_i7.Box<dynamic>? _box) =>
      super.noSuchMethod(Invocation.setter(#box, _box),
          returnValueForMissingStub: null);
  @override
  void insertCharacter(_i10.Character? character) =>
      super.noSuchMethod(Invocation.method(#insertCharacter, [character]),
          returnValueForMissingStub: null);
  @override
  void addEquipmentToCharacter(
          _i10.Character? character, _i11.Equipment? equipment) =>
      super.noSuchMethod(
          Invocation.method(#addEquipmentToCharacter, [character, equipment]),
          returnValueForMissingStub: null);
  @override
  void removeEquipmentFromCharacter(
          _i10.Character? character, _i11.Equipment? equipment) =>
      super.noSuchMethod(
          Invocation.method(
              #removeEquipmentFromCharacter, [character, equipment]),
          returnValueForMissingStub: null);
  @override
  void equipItem(_i10.Character? character, _i11.Equipment? equipment) =>
      super.noSuchMethod(Invocation.method(#equipItem, [character, equipment]),
          returnValueForMissingStub: null);
  @override
  void unequipItem(_i10.Character? character, _i11.Equipment? equipment) =>
      super.noSuchMethod(
          Invocation.method(#unequipItem, [character, equipment]),
          returnValueForMissingStub: null);
  @override
  List<String> getProficientSkillIndexes(_i10.Character? character) => (super
      .noSuchMethod(Invocation.method(#getProficientSkillIndexes, [character]),
          returnValue: <String>[]) as List<String>);
  @override
  List<String> getCharacterEquipmentIndexes(_i10.Character? character) =>
      (super.noSuchMethod(
          Invocation.method(#getCharacterEquipmentIndexes, [character]),
          returnValue: <String>[]) as List<String>);
  @override
  List<String> getCharacterEquippedItemsIndexes(_i10.Character? character) =>
      (super.noSuchMethod(
          Invocation.method(#getCharacterEquippedItemsIndexes, [character]),
          returnValue: <String>[]) as List<String>);
  @override
  void updatePreparedSpells(
          _i10.Character? character, List<_i12.Spell>? spells) =>
      super.noSuchMethod(
          Invocation.method(#updatePreparedSpells, [character, spells]),
          returnValueForMissingStub: null);
  @override
  List<String> getPreparedSpellsIndexes(_i10.Character? character) => (super
      .noSuchMethod(Invocation.method(#getPreparedSpellsIndexes, [character]),
          returnValue: <String>[]) as List<String>);
  @override
  void updateLearnedSpells(
          _i10.Character? character, List<_i12.Spell>? spells) =>
      super.noSuchMethod(
          Invocation.method(#updateLearnedSpells, [character, spells]),
          returnValueForMissingStub: null);
  @override
  List<String> getLearnedSpellsIndexes(_i10.Character? character) => (super
      .noSuchMethod(Invocation.method(#getLearnedSpellsIndexes, [character]),
          returnValue: <String>[]) as List<String>);
  @override
  void useSpellSlot(_i10.Character? character, int? level) =>
      super.noSuchMethod(Invocation.method(#useSpellSlot, [character, level]),
          returnValueForMissingStub: null);
  @override
  void unuseSpellSlot(_i10.Character? character, int? level) =>
      super.noSuchMethod(Invocation.method(#unuseSpellSlot, [character, level]),
          returnValueForMissingStub: null);
  @override
  _i13.Future<Map<int, int>> getUsedSpellSlots(_i10.Character? character) =>
      (super.noSuchMethod(Invocation.method(#getUsedSpellSlots, [character]),
              returnValue: Future<Map<int, int>>.value(<int, int>{}))
          as _i13.Future<Map<int, int>>);
  @override
  _i13.Future<List<_i10.Character>> getCharacters() => (super.noSuchMethod(
          Invocation.method(#getCharacters, []),
          returnValue: Future<List<_i10.Character>>.value(<_i10.Character>[]))
      as _i13.Future<List<_i10.Character>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Class].
///
/// See the documentation for Mockito's code generation for more information.
class MockClass extends _i1.Mock implements _i8.Class {
  MockClass() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: '')
          as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  List<_i14.Characteristic> get savingThrows =>
      (super.noSuchMethod(Invocation.getter(#savingThrows),
          returnValue: <_i14.Characteristic>[]) as List<_i14.Characteristic>);
  @override
  _i8.ProficiencyChoices get proficiencyChoices =>
      (super.noSuchMethod(Invocation.getter(#proficiencyChoices),
          returnValue: _FakeProficiencyChoices_6()) as _i8.ProficiencyChoices);
  @override
  String get imageAsset =>
      (super.noSuchMethod(Invocation.getter(#imageAsset), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Race].
///
/// See the documentation for Mockito's code generation for more information.
class MockRace extends _i1.Mock implements _i15.Race {
  MockRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: '')
          as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get description =>
      (super.noSuchMethod(Invocation.getter(#description), returnValue: '')
          as String);
  @override
  int get baseSpeed =>
      (super.noSuchMethod(Invocation.getter(#baseSpeed), returnValue: 0)
          as int);
  @override
  String get abilityBonusDescription =>
      (super.noSuchMethod(Invocation.getter(#abilityBonusDescription),
          returnValue: '') as String);
  @override
  List<_i15.AbilityBonus> get abilityBonuses =>
      (super.noSuchMethod(Invocation.getter(#abilityBonuses),
          returnValue: <_i15.AbilityBonus>[]) as List<_i15.AbilityBonus>);
  @override
  String get age =>
      (super.noSuchMethod(Invocation.getter(#age), returnValue: '') as String);
  @override
  String get alignment =>
      (super.noSuchMethod(Invocation.getter(#alignment), returnValue: '')
          as String);
  @override
  _i15.Size get size => (super.noSuchMethod(Invocation.getter(#size),
      returnValue: _i15.Size.SMALL) as _i15.Size);
  @override
  String get sizeDescription =>
      (super.noSuchMethod(Invocation.getter(#sizeDescription), returnValue: '')
          as String);
  @override
  String get languagesDescription =>
      (super.noSuchMethod(Invocation.getter(#languagesDescription),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Trait].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrait extends _i1.Mock implements _i16.Trait {
  MockTrait() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: '')
          as String);
  @override
  List<_i16.TraitRace> get races =>
      (super.noSuchMethod(Invocation.getter(#races),
          returnValue: <_i16.TraitRace>[]) as List<_i16.TraitRace>);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  List<String> get description =>
      (super.noSuchMethod(Invocation.getter(#description),
          returnValue: <String>[]) as List<String>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Skill].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkill extends _i1.Mock implements _i17.Skill {
  MockSkill() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: '')
          as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  _i14.Characteristic get characteristic =>
      (super.noSuchMethod(Invocation.getter(#characteristic),
          returnValue: _i14.Characteristic.STRENGTH) as _i14.Characteristic);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  String toString() => super.toString();
}
