const int CHARACTER_TYPE_ADAPTER = 0;
const int RACE_TYPE_ADAPTER = 1;
const int CLASS_TYPE_ADAPTER = 2;
const int ABILITY_BONUS_TYPE_ADAPTER = 3;
const int ABILITY_BONUS_OPTIONS_ADAPTER = 4;
const int SIZE_TYPE_ADAPTER = 5;
const int ABILITY_SCORE_ADAPTER = 6;
