on: push
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # Use the standard Java Action to setup Java 
    - uses: actions/setup-java@v1
      with:
      	# we want the latest Java 12
        java-version: '12.x'
    # Use the community Action to install Flutter
    - uses: subosito/flutter-action@v1
      with:
      	# we want the stable channel
        channel: 'stable'
    # Get flutter packages
    - run: flutter pub get
    - run: flutter test
